BEGIN;
    ALTER TABLE withdrawals ALTER COLUMN sum TYPE INTEGER;
    ALTER TABLE withdrawals ALTER COLUMN sum SET DEFAULT 0;
    ALTER TABLE orders ALTER COLUMN accrual TYPE INTEGER;
    ALTER TABLE orders ALTER COLUMN accrual SET DEFAULT 0;
COMMIT;