BEGIN;
    ALTER TABLE withdrawals ALTER COLUMN sum TYPE NUMERIC(8,2);
    ALTER TABLE withdrawals ALTER COLUMN sum DROP DEFAULT;
    ALTER TABLE orders ALTER COLUMN accrual TYPE NUMERIC(8,2);
    ALTER TABLE orders ALTER COLUMN accrual DROP DEFAULT;
COMMIT;